// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/home/domain/entities/todo_object_box_model_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4260622734256084437),
    name: 'TodoObjectBoxModelEntity',
    lastPropertyId: const obx_int.IdUid(6, 7243426772573303231),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 117322602831108669),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8233619486208023332),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5061782905136694539),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 742520862237296527),
        name: 'whenToComplete',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3343501783091779273),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7243426772573303231),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4260622734256084437),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TodoObjectBoxModelEntity:
        obx_int.EntityDefinition<TodoObjectBoxModelEntity>(
          model: _entities[0],
          toOneRelations: (TodoObjectBoxModelEntity object) => [],
          toManyRelations: (TodoObjectBoxModelEntity object) => {},
          getId: (TodoObjectBoxModelEntity object) => object.id,
          setId: (TodoObjectBoxModelEntity object, int id) {
            object.id = id;
          },
          objectToFB: (TodoObjectBoxModelEntity object, fb.Builder fbb) {
            final titleOffset = fbb.writeString(object.title);
            final subtitleOffset = object.subtitle == null
                ? null
                : fbb.writeString(object.subtitle!);
            final whenToCompleteOffset = fbb.writeString(object.whenToComplete);
            final createdAtOffset = fbb.writeString(object.createdAt);
            fbb.startTable(7);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, titleOffset);
            fbb.addOffset(2, subtitleOffset);
            fbb.addOffset(3, whenToCompleteOffset);
            fbb.addBool(4, object.isCompleted);
            fbb.addOffset(5, createdAtOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final titleParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final subtitleParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 8);
            final whenToCompleteParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final isCompletedParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              12,
              false,
            );
            final createdAtParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final object = TodoObjectBoxModelEntity(
              id: idParam,
              title: titleParam,
              subtitle: subtitleParam,
              whenToComplete: whenToCompleteParam,
              isCompleted: isCompletedParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TodoObjectBoxModelEntity] entity fields to define ObjectBox queries.
class TodoObjectBoxModelEntity_ {
  /// See [TodoObjectBoxModelEntity.id].
  static final id = obx.QueryIntegerProperty<TodoObjectBoxModelEntity>(
    _entities[0].properties[0],
  );

  /// See [TodoObjectBoxModelEntity.title].
  static final title = obx.QueryStringProperty<TodoObjectBoxModelEntity>(
    _entities[0].properties[1],
  );

  /// See [TodoObjectBoxModelEntity.subtitle].
  static final subtitle = obx.QueryStringProperty<TodoObjectBoxModelEntity>(
    _entities[0].properties[2],
  );

  /// See [TodoObjectBoxModelEntity.whenToComplete].
  static final whenToComplete =
      obx.QueryStringProperty<TodoObjectBoxModelEntity>(
        _entities[0].properties[3],
      );

  /// See [TodoObjectBoxModelEntity.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<TodoObjectBoxModelEntity>(
    _entities[0].properties[4],
  );

  /// See [TodoObjectBoxModelEntity.createdAt].
  static final createdAt = obx.QueryStringProperty<TodoObjectBoxModelEntity>(
    _entities[0].properties[5],
  );
}
